<h1>Numpy(Numerical Python)</h1>

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

1D array

In [8]:
arr = np.array([43,23,54,76,1])

In [9]:
type(arr)

numpy.ndarray

2D array

In [10]:
matrix = np.array([[23,34,54],
                   [32,12,23],
                   [56,89,90]])

In [12]:
matrix.ndim

2

In [13]:
tDarray = np.array([[
    [23,45,32],
    [8,5,6],
    [8,6,1]
],
[
    [5,8,9],
    [8,3,7],
    [5,7,3]
],
[
    [45,34,84],
    [56,98,3],
    [9,0,7]
]

])

In [14]:
tDarray.ndim

3

In [16]:
matrix.dtype

dtype('int64')

In [18]:
matrix.size

9

In [ ]:
matrix.itemsize #space occupied by memory per element

8

In [20]:
matrix.nbytes

72

In [21]:
arr.shape

(5,)

In [22]:
matrix.shape

(3, 3)

Create Arrays

In [23]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.empty((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.arange(2,8,2)

array([2, 4, 6])

In [32]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [34]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

Mathematical Calculation

In [36]:
a= np.array([3,2,5,2,5,6])
b= np.array([5,3,9,6,2,1])

In [37]:
a + b

array([ 8,  5, 14,  8,  7,  7])

In [38]:
a * b

array([15,  6, 45, 12, 10,  6])

In [39]:
a - b

array([-2, -1, -4, -4,  3,  5])

In [41]:
a // b

array([0, 0, 0, 0, 2, 6])

In [42]:
np.add(a,b)

array([ 8,  5, 14,  8,  7,  7])

In [43]:
np.subtract(a,b)

array([-2, -1, -4, -4,  3,  5])

In [44]:
np.multiply(a,b)

array([15,  6, 45, 12, 10,  6])

In [45]:
a * 3

array([ 9,  6, 15,  6, 15, 18])

Aggregation functions

In [46]:
arr.min()

np.int64(1)

In [47]:
matrix.min()

np.int64(12)

In [48]:
matrix.sum()

np.int64(413)

In [49]:
matrix.mean()

np.float64(45.888888888888886)

In [50]:
matrix.max()

np.int64(90)

In [51]:
arr.argmax()

np.int64(3)

In [52]:
arr.argmin()

np.int64(4)

<h2>Reshape</h2>

In [53]:
arr = np.array([3,5,2,5,7,2,4,6,8])

In [54]:
arr.reshape((3,3))

array([[3, 5, 2],
       [5, 7, 2],
       [4, 6, 8]])

In [55]:
matrix= np.array([[3, 5, 2],
       [5, 7, 2],
       [4, 6, 8]])

In [59]:
arr.reshape(1,9)

array([[3, 5, 2, 5, 7, 2, 4, 6, 8]])

In [60]:
matrix

array([[3, 5, 2],
       [5, 7, 2],
       [4, 6, 8]])

<h2>Flatten matrix</h2>

In [61]:
matrix.flatten()

array([3, 5, 2, 5, 7, 2, 4, 6, 8])

In [62]:
matrix.reshape(9,)

array([3, 5, 2, 5, 7, 2, 4, 6, 8])

In [63]:
matrix.ravel()

array([3, 5, 2, 5, 7, 2, 4, 6, 8])

<h1>sort arrays</h1>

In [64]:
arr = np.array([3,5,2,5,7,2,4,6,8])

In [65]:
np.sort(arr)

array([2, 2, 3, 4, 5, 5, 6, 7, 8])

In [67]:
matrix

array([[3, 5, 2],
       [5, 7, 2],
       [4, 6, 8]])

In [71]:
np.sort(matrix,axis=1,kind='mergesort')

array([[2, 3, 5],
       [2, 5, 7],
       [4, 6, 8]])