<h2>VSTACK & HSTACK</h2>

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,5,2,6])
b = np.array([4,5,6,7,7])

In [3]:
mat1 = np.array([
    [1,2,3],
    [4,5,6],
    [6,5,2]
])

mat2 = np.array([
    [4,5,6],
    [9,8,6],
    [0,3,5]])

In [4]:
np.vstack((a,b))

array([[2, 3, 5, 2, 6],
       [4, 5, 6, 7, 7]])

In [ ]:
np.vstack((mat1,mat2)) # in vstack number of columns should be same, rows may vary

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 2],
       [4, 5, 6],
       [9, 8, 6],
       [0, 3, 5]])

In [12]:
np.hstack((a,b))

array([2, 3, 5, 2, 6, 4, 5, 6, 7, 7])

In [17]:
np.hstack((mat1,mat2)) # number of rows should be equal

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 9, 8, 6],
       [6, 5, 2, 0, 3, 5]])

<h2>HSPLIT</h2>

In [19]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 2]])

In [21]:
np.hsplit(mat1,3)

[array([[1],
        [4],
        [6]]),
 array([[2],
        [5],
        [5]]),
 array([[3],
        [6],
        [2]])]

In [23]:
mat3 = np.array(
    [
        [2,3,4,1],
        [5,9,2,5],
        [3,2,5,2]
    ]
)

In [28]:
np.hsplit(mat3,2)

[array([[2, 3],
        [5, 9],
        [3, 2]]),
 array([[4, 1],
        [2, 5],
        [5, 2]])]

<h1>Broadcasting</h1>

Scaler calculation with np array / vector

In [32]:
a

array([2, 3, 5, 2, 6])

In [30]:
a * 4

array([ 8, 12, 20,  8, 24])

In [31]:
a + 7

array([ 9, 10, 12,  9, 13])

Vector calculation

In [34]:
a

array([2, 3, 5, 2, 6])

In [35]:
b

array([4, 5, 6, 7, 7])

In [33]:
a * b

array([ 8, 15, 30, 14, 42])

In [38]:
arr = np.array([3,4,1])

In [40]:
arr.shape

(3,)

In [41]:
mat1.shape

(3, 3)

(n,m) (n,)

(n,m) (,m)

In [ ]:
(3,2) (2,)

In [42]:
col = np.array([
    [2],
    [3],
    [8]])

In [45]:
cols = np.array([
    [2,3],
    [3,1],
    [8,7]])

In [43]:
col.shape

(3, 1)

In [39]:
mat1 * arr

array([[ 3,  8,  3],
       [12, 20,  6],
       [18, 20,  2]])

In [4]:
mat1*cols

NameError: name 'cols' is not defined

<h1>Random Number</h1>

New Method

In [50]:
from numpy.random import default_rng

In [51]:
rng = default_rng()

In [57]:
rng.random() # 0 -1

0.9752399336586632

Old method

In [48]:
np.random.rand()

0.8214808349603805

In [ ]:
np.random.rand(5)#old method

array([0.23286575, 0.76934838, 0.69793309, 0.49546291, 0.28527357])

In [72]:
rng.random(5) #new method

array([0.96309973, 0.55882636, 0.44536072, 0.89102668, 0.58744553])

Integers

In [140]:
rng.integers(1,7)

np.int64(3)

In [166]:
rng.integers(1,10,size=10)

array([9, 1, 8, 5, 8, 5, 8, 6, 7, 1])

In [197]:
rng.normal(loc=0,scale=1,size=5)

array([-1.43777383,  1.20680846, -0.78285447,  0.49727374,  0.39827702])

Uniform distribution

In [207]:
rng.uniform(10,20,size=5)

array([13.17231084, 18.93452338, 10.25772947, 19.36258987, 11.91241632])

Random sampling

Choice

In [222]:
arr =[10,20,30,40]

rng.choice(arr)

np.int64(20)

In [228]:
rng.choice(arr,size=5)

array([40, 40, 40, 30, 40])

In [ ]:
arr = np.array([1,2,3,4])
rng.shuffle(arr) # modifies original array

In [230]:
arr

array([1, 3, 4, 2])

In [ ]:
arr = np.array([4,5,6,7])

rng.permutation(arr) # returns new array.. do not change orignal one

array([6, 7, 4, 5])

In [232]:
arr

array([4, 5, 6, 7])

<h1>Seed</h1>

In [ ]:
rng = default_rng(42) #same output every time because of seed value 

rng.integers(10,30,size=30)

array([11, 25, 23, 18, 18, 27, 11, 23, 14, 11, 20, 29, 24, 25, 24, 25, 20,
       12, 26, 19, 20, 17, 13, 28, 25, 22, 18, 26, 20, 18])

In [291]:
rng.integers(10,20,size=30)

array([19, 17, 18, 18, 19, 11, 18, 10, 14, 15, 13, 11, 11, 18, 13, 13, 19,
       11, 19, 19, 15, 11, 11, 12, 15, 11, 14, 11, 15, 10])

Binomial Distribution

In [312]:
rng.binomial(n=10,p=0.5,size=5)

array([6, 4, 4, 4, 3])

In [315]:
rng.random((3,3,3))

array([[[0.82539951, 0.29535903, 0.45854808],
        [0.44231413, 0.30192739, 0.9184419 ],
        [0.78129404, 0.11058841, 0.99703466]],

       [[0.87920002, 0.28390844, 0.83689658],
        [0.10641953, 0.99910473, 0.66568474],
        [0.65012502, 0.09044073, 0.8970334 ]],

       [[0.0289995 , 0.24082806, 0.14302188],
        [0.77676794, 0.19820423, 0.91063823],
        [0.65626904, 0.03616271, 0.00542983]]])

In [318]:
rng.integers(1,6,size=(3,3,3))

array([[[5, 5, 1],
        [4, 5, 4],
        [5, 5, 3]],

       [[1, 3, 2],
        [1, 1, 4],
        [3, 3, 4]],

       [[3, 4, 1],
        [5, 3, 1],
        [5, 4, 1]]])

Dummy Dataset

Age,Salary, Gender, Purchased

In [319]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [320]:
import pandas as pd

In [324]:
rng = default_rng(42)

n = 100

age = rng.integers(18,60,size=n)
salary = rng.integers(20000,120000,size=n)
gender = rng.choice(['male','female','other'],size=n)
purchased_prob = (age/60) + (salary/120000)
print(purchased_prob[:6])
purchase_prob = purchased_prob / purchased_prob.max()
print(purchase_prob[:6])
purchased = rng.binomial(1,purchase_prob)

df = pd.DataFrame({
    "Age":age,
    "Salary":salary,
    "Gender":gender,
    "Purchased":purchased
})

[1.21060833 1.16658333 1.58740833 0.7728     1.4307     1.72243333]
[0.62723112 0.60442123 0.82245585 0.40039722 0.74126333 0.89241397]


In [323]:
df.head()

,Age,Salary,Gender,Purchased
0,21,103273,female,0
1,50,39990,other,0
2,45,100489,female,1
3,36,20736,other,0
4,36,99684,female,1
