## Numpy

In [2]:
!pip3 install numpy
!pip3 install --upgrade pip


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3


In [1]:
import numpy as np


In [77]:
#1D array

arr = np.array([23,45,67,23])
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
lst = [45,34,67,90,23]
arr = np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
#2D array

mat = [[2,3,4],
       [4,5,6],
       [7,8,9]]

matrix = np.array(mat)
print(matrix)
print(type(matrix))
print(matrix.ndim)
print(arr.ndim)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
1


<h2><strong>Attributes<strong></h2>

In [13]:
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)
print(matrix.shape)
print(matrix.itemsize)
print(matrix.nbytes)

2
9
int64
(3, 3)
8
72


In [ ]:
matrix.T #transpose the matrix

array([[2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

In [17]:
list(matrix.flat)

[np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

<h2><strong>create basic matrix</strong></h2>

In [25]:
print(np.zeros(3)) #1D array
print(np.zeros((2,3))) #2D array

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones(3)) #1D array
np.ones((3,4)) #2D array

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
np.ones((3,3,3))


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [45]:
np.arange(1,10)

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.linspace(1,2,num=100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [53]:
np.sort(arr,kind='stable')

array([23, 34, 45, 67, 90])

In [ ]:
values = [('Arthur', 1.8, 41), 
          ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]

In [61]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]

In [62]:
data= np.array(values,dtype= dtype)
print(data)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [64]:
np.sort(data,order='name')

array([(b'Arthur', 1.8, 41), (b'Galahad', 1.7, 38),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

<h2>Concate</h2>

In [73]:
arr1 = np.array([[34,83],
                 [29,10]])
arr2 = np.array([[45,89],
                 [23,1]])

np.concatenate((arr1,arr2),axis=0)

array([[34, 83],
       [29, 10],
       [45, 89],
       [23,  1]])

In [81]:
print(arr)
a2 = arr[np.newaxis,:]
print(a2)

[23 45 67 23]
[[23 45 67 23]]


Generate random numbers

In [ ]:
np.random.rand(12) # we use it generate n numbers of random numbers

array([0.08498016, 0.68239958, 0.58544948, 0.25646436, 0.68570328,
       0.27633394, 0.01807041, 0.75254588, 0.51777549, 0.63129548,
       0.15337553, 0.67231752])

In [5]:
np.random.rand(2,3)

array([[0.66679193, 0.85374432, 0.71026112],
       [0.55262792, 0.77992472, 0.20388308]])

Generate Random integers

In [46]:
np.random.randint(1,6)

3

In [67]:
np.random.randint(1,10,5)

array([3, 9, 7, 3, 8])

In [75]:
np.random.randint(1,10,(3,3,3,3))

array([[[[6, 8, 9],
         [2, 7, 1],
         [4, 1, 8]],

        [[4, 5, 3],
         [6, 7, 1],
         [6, 6, 4]],

        [[2, 9, 3],
         [4, 7, 3],
         [9, 3, 5]]],


       [[[1, 9, 4],
         [1, 7, 1],
         [5, 8, 3]],

        [[8, 8, 2],
         [9, 6, 3],
         [7, 9, 1]],

        [[9, 7, 5],
         [9, 7, 5],
         [9, 9, 3]]],


       [[[6, 3, 3],
         [7, 3, 3],
         [4, 5, 9]],

        [[1, 7, 8],
         [7, 5, 2],
         [2, 2, 4]],

        [[8, 8, 7],
         [6, 4, 9],
         [8, 9, 6]]]])

Random choice (sampling)

In [81]:
np.random.choice([2,6,9,0,1])

np.int64(9)

In [91]:
np.random.choice([2,6,9,0,1],10)


array([2, 1, 0, 9, 6, 9, 6, 6, 2, 0])

In [95]:
np.random.choice([1,2,3],size=10, p = [0.1,0.3,0.6])

array([3, 2, 3, 3, 2, 2, 1, 2, 3, 3])

Random shuffle

In [113]:
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[6 3 1 4 2 5]


Random permutation

<code>Similar to shuffle but does not nodify original array.
Original array remains unchanged</code>

In [109]:
arr = np.array([1,2,3,4,5,6])
print(np.random.permutation(arr))

print(arr)

[2 4 3 1 5 6]
[1 2 3 4 5 6]


Setting random seed

Output will always remain same.
this is extremely important in machine learning.

In [204]:
np.random.seed(42)

np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

Normal distribution

In [223]:
np.random.randn()

-0.005527862320126283

when you want to assign the mean and standard deviation then you will use np.ranom.normal

In [ ]:
np.random.seed(30)
np.random.normal(loc=50,scale=10,size=5) # loc -> mean, scale -> standard deviation

array([37.35947335, 65.27905352, 40.29289062, 54.70559616, 48.99303284])

Uniform distribution

In [251]:
np.random.uniform(low=10, high=20,size=13)

array([12.35057896, 15.85694269, 14.06690102, 11.36234322, 15.44136288,
       15.18176347, 17.66855106, 19.33850143, 10.89703383, 11.95771257,
       19.94193684, 12.35180498, 12.38986372])

Binomial distribution

Used for success and failure experiments:
Example:
 - tossing coin
 - Ad click prediction
 - Email open rate

In [312]:
np.random.binomial(10,0.5,5)

array([6, 7, 5, 4, 7])

Poisson Distribution

In [320]:
np.random.poisson(lam=5,size=10)

array([ 6,  3,  7,  7,  5,  5,  6,  6, 12,  6])

Random sampling from the data

In [321]:
data = np.array([10,20,30,40,50,60,70,80,90])

In [322]:
np.random.choice(data,size=3)

array([70, 40, 50])

General random dataset for ml

In [325]:
features = np.random.rand(100,3)
target = np.random.randint(0,50,100)

print(features[:5])
print(target[:5])

[[0.27601808 0.91311839 0.74615907]
 [0.42245838 0.25436492 0.77846238]
 [0.01216331 0.50409645 0.22825212]
 [0.44089059 0.25262807 0.14861917]
 [0.31058965 0.24272142 0.88160704]]
[ 1  2 49 41 28]
