## Numpy

In [2]:
!pip3 install numpy
!pip3 install --upgrade pip


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3


In [3]:
import numpy as np


In [77]:
#1D array

arr = np.array([23,45,67,23])
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
lst = [45,34,67,90,23]
arr = np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
#2D array

mat = [[2,3,4],
       [4,5,6],
       [7,8,9]]

matrix = np.array(mat)
print(matrix)
print(type(matrix))
print(matrix.ndim)
print(arr.ndim)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
1


<h2><strong>Attributes<strong></h2>

In [13]:
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype)
print(matrix.shape)
print(matrix.itemsize)
print(matrix.nbytes)

2
9
int64
(3, 3)
8
72


In [ ]:
matrix.T #transpose the matrix

array([[2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

In [17]:
list(matrix.flat)

[np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

<h2><strong>create basic matrix</strong></h2>

In [25]:
print(np.zeros(3)) #1D array
print(np.zeros((2,3))) #2D array

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones(3)) #1D array
np.ones((3,4)) #2D array

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
np.ones((3,3,3))


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [45]:
np.arange(1,10)

np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.linspace(1,2,num=100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [53]:
np.sort(arr,kind='stable')

array([23, 34, 45, 67, 90])

In [ ]:
values = [('Arthur', 1.8, 41), 
          ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]

In [61]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]

In [62]:
data= np.array(values,dtype= dtype)
print(data)

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


In [64]:
np.sort(data,order='name')

array([(b'Arthur', 1.8, 41), (b'Galahad', 1.7, 38),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

<h2>Concate</h2>

In [73]:
arr1 = np.array([[34,83],
                 [29,10]])
arr2 = np.array([[45,89],
                 [23,1]])

np.concatenate((arr1,arr2),axis=0)

array([[34, 83],
       [29, 10],
       [45, 89],
       [23,  1]])

In [81]:
print(arr)
a2 = arr[np.newaxis,:]
print(a2)

[23 45 67 23]
[[23 45 67 23]]
