<h2><strong>What is Logistic Regression?</strong></h2>

Logistic Regression is a supervised machine learning algorithm used for classification problems.

Unlike linear regression which predicts continuous values, logistic regression predicts probabilities of classes.

Example problems:

|Problem	|Target|
|-------|------|
|Email spam detection	|Spam / Not Spam|
|Disease prediction	|Sick / Healthy|
|Customer churn	|Leave / Stay|
|Fraud detection	|Fraud / Not Fraud|

So logistic regression answers:

What is the probability that this data belongs to class 1?

<h2><strong>Why Do We Need Logistic Regression?</strong></h2>

If we try to use Linear Regression for classification, problems occur.

Example:

Suppose we predict if a student passes (1) or fails (0).

Linear regression might predict:

- 1.2

- -0.3

But probabilities must lie between:

0≤P≤1

Linear regression cannot guarantee that.

Therefore we use a function that compresses values between 0 and 1.

This is where the Sigmoid Function comes in.

<h2><strong>Sigmoid Function (Logistic Function)</strong></h2>

The sigmoid function converts any real value into a probability.

![sigmoid diagram](/Machine-Learning-Batches/MLPractice/diagrams/img01.JPG)

P(y=1|x) = \frac{1}{1 + e^{-(\beta_0 + \beta_1 x)}}

Where:

|Symbol|	Meaning|
|------|-------|
|β0	|Intercept|
|β1	|Coefficient|
|x	|input feature|

The sigmoid curve looks like an S-shaped curve.

Properties:
- Output between 0 and 1
- Used to represent probability

Decision boundary:

- if probability >= 0.5 → Class 1
- if probability < 0.5 → Class 0

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 

In [8]:
X,y = make_classification(n_samples=1000,n_features=10,n_classes= 2,n_informative =5 ,random_state=42)

In [10]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [11]:
logistic = LogisticRegression()
model = logistic.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [14]:
y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
model.predict_proba(x_test)# whatever probability will be high that data point will occur ex:[00.93379948, 0.06620052]->0, if [0.23850403, 0.76149597]->1

array([[0.93379948, 0.06620052],
       [0.23850403, 0.76149597],
       [0.84257502, 0.15742498],
       [0.95624025, 0.04375975],
       [0.60880453, 0.39119547],
       [0.75898748, 0.24101252],
       [0.88134921, 0.11865079],
       [0.35497027, 0.64502973],
       [0.21329977, 0.78670023],
       [0.28993395, 0.71006605],
       [0.13222511, 0.86777489],
       [0.36432917, 0.63567083],
       [0.50582253, 0.49417747],
       [0.34861135, 0.65138865],
       [0.65588479, 0.34411521],
       [0.38903094, 0.61096906],
       [0.02014805, 0.97985195],
       [0.49664643, 0.50335357],
       [0.78858043, 0.21141957],
       [0.94332065, 0.05667935],
       [0.94206791, 0.05793209],
       [0.96791813, 0.03208187],
       [0.79072031, 0.20927969],
       [0.56807205, 0.43192795],
       [0.99474974, 0.00525026],
       [0.21119751, 0.78880249],
       [0.48273877, 0.51726123],
       [0.85362365, 0.14637635],
       [0.8142497 , 0.1857503 ],
       [0.65364574, 0.34635426],
       [0.

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [18]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8233333333333334
[[135  23]
 [ 30 112]]
              precision    recall  f1-score   support

           0       0.82      0.85      0.84       158
           1       0.83      0.79      0.81       142

    accuracy                           0.82       300
   macro avg       0.82      0.82      0.82       300
weighted avg       0.82      0.82      0.82       300

